process {
  title: 'node',
  version: 'v6.2.1',
  moduleLoadList:
   [ 'Binding contextify',
     'Binding natives',
     'NativeModule events',
     'NativeModule util',
     'Binding uv',
     'NativeModule buffer',
     'Binding buffer',
     'NativeModule internal/util',
     'Binding util',
     'NativeModule timers',
     'Binding timer_wrap',
     'NativeModule internal/linkedlist',
     'NativeModule assert',
     'NativeModule internal/process',
     'Binding config',
     'NativeModule internal/process/warning',
     'NativeModule internal/process/next_tick',
     'NativeModule internal/process/promises',
     'NativeModule internal/process/stdio',
     'NativeModule tty',
     'NativeModule net',
     'NativeModule stream',
     'NativeModule _stream_readable',
     'NativeModule _stream_writable',
     'NativeModule _stream_duplex',
     'NativeModule _stream_transform',
     'NativeModule _stream_passthrough',
     'NativeModule internal/net',
     'Binding cares_wrap',
     'Binding tty_wrap',
     'Binding tcp_wrap',
     'Binding pipe_wrap',
     'Binding stream_wrap',
     'NativeModule internal/repl',
     'NativeModule readline',
     'NativeModule internal/readline',
     'NativeModule repl',
     'NativeModule internal/module',
     'NativeModule vm',
     'NativeModule path',
     'NativeModule fs',
     'Binding fs',
     'NativeModule constants',
     'Binding constants',
     'Binding fs_event_wrap',
     'NativeModule console',
     'Binding signal_wrap',
     'NativeModule module',
     'NativeModule domain',
     'NativeModule os',
     'Binding os',
     'NativeModule string_decoder' ],
  versions:
   { http_parser: '2.7.0',
     node: '6.2.1',
     v8: '5.0.71.52',
     uv: '1.9.1',
     zlib: '1.2.8',
     ares: '1.10.1-DEV',
     icu: '56.1',
     modules: '48',
     openssl: '1.0.2h' },
  arch: 'x64',
  platform: 'linux',
  release:
   { name: 'node',
     sourceUrl: 'https://nodejs.org/download/release/v6.2.1/node-v6.2.1.tar.gz',
     headersUrl: 'https://nodejs.org/download/release/v6.2.1/node-v6.2.1-headers.tar.gz' },
  argv: [ '/usr/bin/nodejs' ],
  execArgv: [],
  env:
   { NVM_RC_VERSION: '',
     LC_PAPER: 'fr_FR.UTF-8',
     LC_ADDRESS: 'fr_FR.UTF-8',
     LC_MONETARY: 'fr_FR.UTF-8',
     NVM_CD_FLAGS: '',
     SHELL: '/bin/bash',
     TERM: 'xterm',
     LC_NUMERIC: 'fr_FR.UTF-8',
     NVM_DIR: '/root/.nvm',
     USER: 'root',
     LC_TELEPHONE: 'fr_FR.UTF-8',
     LS_COLORS: 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:',
     SUDO_USER: 'jamal',
     SUDO_UID: '1000',
     USERNAME: 'root',
     MAIL: '/var/mail/root',
     PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
     NVM_NODEJS_ORG_MIRROR: 'https://nodejs.org/dist',
     LC_IDENTIFICATION: 'fr_FR.UTF-8',
     PWD: '/home/jamal/Desktop/dev-runtime-nodejs',
     LANG: 'en_US.UTF-8',
     LC_MEASUREMENT: 'fr_FR.UTF-8',
     SHLVL: '1',
     SUDO_COMMAND: '/bin/bash',
     HOME: '/root',
     LANGUAGE: 'en_US',
     LOGNAME: 'root',
     LESSOPEN: '| /usr/bin/lesspipe %s',
     NVM_IOJS_ORG_MIRROR: 'https://iojs.org/dist',
     SUDO_GID: '1000',
     DISPLAY: ':0',
     LESSCLOSE: '/usr/bin/lesspipe %s %s',
     LC_TIME: 'fr_FR.UTF-8',
     LC_NAME: 'fr_FR.UTF-8',
     XAUTHORITY: '/home/jamal/.Xauthority',
     COLORTERM: 'gnome-terminal',
     _: '/usr/bin/node',
     OLDPWD: '/home/jamal/Desktop' },
  pid: 14330,
  features:
   { debug: false,
     uv: true,
     ipv6: true,
     tls_npn: true,
     tls_alpn: true,
     tls_sni: true,
     tls_ocsp: true,
     tls: true },
  _needImmediateCallback: false,
  execPath: '/usr/bin/nodejs',
  debugPort: 5858,
  _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
  _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
  _getActiveRequests: [Function: _getActiveRequests],
  _getActiveHandles: [Function: _getActiveHandles],
  reallyExit: [Function: reallyExit],
  abort: [Function: abort],
  chdir: [Function: chdir],
  cwd: [Function: cwd],
  umask: [Function: umask],
  getuid: [Function: getuid],
  geteuid: [Function: geteuid],
  setuid: [Function: setuid],
  seteuid: [Function: seteuid],
  setgid: [Function: setgid],
  setegid: [Function: setegid],
  getgid: [Function: getgid],
  getegid: [Function: getegid],
  getgroups: [Function: getgroups],
  setgroups: [Function: setgroups],
  initgroups: [Function: initgroups],
  _kill: [Function: _kill],
  _debugProcess: [Function: _debugProcess],
  _debugPause: [Function: _debugPause],
  _debugEnd: [Function: _debugEnd],
  hrtime: [Function: hrtime],
  cpuUsage: [Function: cpuUsage],
  dlopen: [Function: dlopen],
  uptime: [Function: uptime],
  memoryUsage: [Function: memoryUsage],
  binding: [Function: binding],
  _linkedBinding: [Function: _linkedBinding],
  _events:
   { warning: [Function],
     newListener: [Function],
     removeListener: [Function],
     SIGWINCH: [ [Function], [Function] ] },
  _rawDebug: [Function],
  _eventsCount: 4,
  domain: [Getter/Setter],
  _maxListeners: undefined,
  _fatalException: [Function],
  _exiting: false,
  assert: [Function],
  config:
   { target_defaults:
      { cflags: [],
        default_configuration: 'Release',
        defines: [],
        include_dirs: [],
        libraries: [] },
     variables:
      { asan: 0,
        gas_version: '2.24',
        host_arch: 'x64',
        icu_data_file: 'icudt56l.dat',
        icu_data_in: '../../deps/icu/source/data/in/icudt56l.dat',
        icu_endianness: 'l',
        icu_gyp_path: 'tools/icu/icu-generic.gyp',
        icu_locales: 'en,root',
        icu_path: 'deps/icu',
        icu_small: true,
        icu_ver_major: '56',
        node_byteorder: 'little',
        node_enable_v8_vtunejit: false,
        node_install_npm: true,
        node_no_browser_globals: false,
        node_prefix: '/usr',
        node_release_urlbase: '',
        node_shared_cares: false,
        node_shared_http_parser: false,
        node_shared_libuv: false,
        node_shared_openssl: false,
        node_shared_zlib: false,
        node_tag: '',
        node_use_dtrace: false,
        node_use_etw: false,
        node_use_lttng: false,
        node_use_openssl: true,
        node_use_perfctr: false,
        openssl_fips: '',
        openssl_no_asm: 0,
        target_arch: 'x64',
        uv_parent_path: '/deps/uv/',
        uv_use_dtrace: false,
        v8_enable_gdbjit: 0,
        v8_enable_i18n_support: 1,
        v8_no_strict_aliasing: 1,
        v8_optimized_debug: 0,
        v8_random_seed: 0,
        v8_use_snapshot: true,
        want_separate_host_toolset: 0 } },
  emitWarning: [Function],
  nextTick: [Function: nextTick],
  _tickCallback: [Function: _tickDomainCallback],
  _tickDomainCallback: [Function: _tickDomainCallback],
  stdout: [Getter],
  stderr: [Getter],
  stdin: [Getter],
  openStdin: [Function],
  exit: [Function],
  kill: [Function] }
>
